apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-controller-v2
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    repoURL: https://github.com/actions/actions-runner-controller
    targetRevision: gha-runner-scale-set-0.14.2
    chart: charts/gha-runner-scale-set-controller
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Delete=confirm
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
      - ServerSideDiff=false
