appName: foundation-external-dns
chartPath: charts/foundation/external-dns
releaseName: external-dns
namespace: external-dns
syncWave: "0"

external-dns-private:
  fullnameOverride: external-dns-private
  serviceAccount:
    name: external-dns-private
  domainFilters:
    - jinjin99.xyz
  sources:
    - gateway-httproute
  provider:
    name: aws
  policy: sync
  interval: 1m
  txtOwnerId: sandbox-private
  extraArgs:
    - --aws-zone-type=private
    - --gateway-name=private-gateway
  env:
    - name: AWS_DEFAULT_REGION
      value: ap-northeast-2
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
      effect: NoSchedule

external-dns-public:
  fullnameOverride: external-dns-public
  serviceAccount:
    name: external-dns-public
  domainFilters:
    - jinjin99.xyz
  sources:
    - gateway-httproute
  provider:
    name: aws
  policy: sync
  interval: 1m
  txtOwnerId: sandbox-public
  extraArgs:
    - --aws-zone-type=public
    - --gateway-name=public-gateway
  env:
    - name: AWS_DEFAULT_REGION
      value: ap-northeast-2
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
      effect: NoSchedule
