# $schema: https://raw.githubusercontent.com/terrakube-io/terrakube-helm-chart/refs/heads/main/charts/terrakube/values.schema.json

name: terrakube

enableIPv6: false

security:
  useOpenLDAP: false
  adminGroup: "jinops-cloud:admins"
  dexClientId: "terrakube-ui"
  dexClientScope: "email openid profile offline_access groups"
  existingSecret: false

dex:
  enabled: true
  existingSecret: false
  revisionHistoryLimit: 3
  envFrom:
    - secretRef:
        name: terrakube-dex-github
  config:
    issuer: https://terrakube-api.jinops.cloud/dex
    storage:
      type: memory
    web:
      http: 0.0.0.0:5556
      allowedOrigins: ['*']
    oauth2:
      responseTypes: ["code", "token", "id_token"]
      skipApprovalScreen: true
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: $GITHUB_CLIENT_ID
          clientSecret: $GITHUB_CLIENT_SECRET
          redirectURI: https://terrakube-api.jinops.cloud/dex/callback
          teamNameField: slug
          orgs:
            - name: jinops-cloud
    staticClients:
      - id: terrakube-ui
        name: Terrakube UI
        public: true
        redirectURIs:
          - https://terrakube.jinops.cloud
          - /device/callback
          - http://localhost:10000/login
          - http://localhost:10001/login

storage:
  defaultStorage: false
  aws:
    bucketName: "deokjong-terrakube-storage"
    region: "ap-northeast-2"
    accessKey: ""
    secretKey: ""

api:
  enabled: true
  existingSecret: true
  replicaCount: "1"
  serviceAccountName: "terrakube"
  rbac:
    create: true
    roleName: "terrakube-api-role"
    roleBindingName: "terrakube-api-role-binding"
  ephemeralExecution:
    enabled: true
    secretName:
      - terrakube-executor-secrets
  defaultDatabase: true
  defaultRedis: true
  loadSampleData: false
  resources:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      memory: 2Gi
  properties:
    redisPort: "6379"
  env:
    - name: AwsEnableRoleAuth
      value: "true"

executor:
  enabled: true
  existingSecret: true
  replicaCount: "0"
  serviceAccountName: "terrakube"
  resources:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      memory: 2Gi
  env:
    - name: AwsEnableRoleAuth
      value: "true"
    - name: AwsIncludeBackendKeys
      value: "false"

registry:
  enabled: true
  existingSecret: true
  replicaCount: "1"
  serviceAccountName: "terrakube"
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 1Gi
  env:
    - name: AwsEnableRoleAuth
      value: "true"

ui:
  enabled: true
  existingSecret: false
  replicaCount: "1"
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 256Mi

postgresql:
  auth:
    username: "terrakube"
    database: "terrakube"
    existingSecret: "terrakube-postgresql"
    secretKeys:
      adminPasswordKey: postgres-password
      userPasswordKey: password

valkey:
  auth:
    enabled: true
    usersExistingSecret: "terrakube-valkey"
    aclUsers:
      default:
        permissions: "~* &* +@all"
        password: ""

ingress:
  useTls: true
  controller: "gatewayapi"
  gatewayapi:
    enabled: true
    apiVersion: v1
    gateways:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: istio-gateway
        namespace: istio-system

  ui:
    enabled: true
    domain: "terrakube.jinops.cloud"
    path: "/"
    annotations:
      nginx.ingress.kubernetes.io/use-regex: null

  api:
    enabled: true
    domain: "terrakube-api.jinops.cloud"
    path: "/"
    annotations:
      nginx.ingress.kubernetes.io/use-regex: null
      nginx.ingress.kubernetes.io/proxy-set-headers: null

  registry:
    enabled: true
    domain: "terrakube-reg.jinops.cloud"
    path: "/"
    annotations:
      nginx.ingress.kubernetes.io/use-regex: null
      nginx.ingress.kubernetes.io/proxy-set-headers: null

  dex:
    enabled: true
    path: "/dex/"

  executor:
    enabled: false
