route:
  enabled: true
  name: ""
  namespace: ""
  hostnames: []
  gatewayType: public # or private or all
  gatewayOverride: []
  backendRefs:
    - name: ""
      group: ""
      port: 80
      weight: 1
  matches:
    - path:
        type: PathPrefix
        value: /
  filters: []
  redirect:
    enabled: true
    statusCode: 301
