apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-cni
spec:
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: cni
    targetRevision: 1.30.0
    helm:
      valuesObject:
        profile: ambient
  destination:
    namespace: istio-system
  project: default
