apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.global.clusterName }}
  namespace: {{ .Release.Namespace }}
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: {{ .Values.global.repoURL }}
        revision: {{ .Values.global.targetRevision }}
        files:
          - path: "{{ .Values.global.basePath }}/**/app.yaml"
  template:
    metadata:
      name: '{{`{{ .appName }}`}}'
      namespace: {{ .Release.Namespace }}
      annotations:
        argocd.argoproj.io/sync-wave: '{{`{{ dig "syncWave" "0" . }}`}}'
    spec:
      project: {{ .Values.global.project }}
      sources:
        - repoURL: {{ .Values.global.repoURL }}
          targetRevision: {{ .Values.global.targetRevision }}
          path: '{{`{{ dig "chartPath" (printf "charts/%s" (trimPrefix "`}}{{ .Values.global.basePath }}/{{`" (index .path "path"))) . }}`}}'
          helm:
            releaseName: '{{`{{ dig "releaseName" (index .path "path" | base) . }}`}}'
            valueFiles:
              - $values/{{ .Values.global.basePath }}/config.yaml
              - $values/{{`{{ index .path "path" }}`}}/values.yaml
            ignoreMissingValueFiles: true
        - repoURL: {{ .Values.global.repoURL }}
          targetRevision: {{ .Values.global.targetRevision }}
          ref: values
      destination:
        server: {{ .Values.global.destination.server }}
        namespace: '{{`{{ .namespace }}`}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
  templatePatch: |
    {{`{{- if and (hasKey . "enabled") (not .enabled) }}`}}
    metadata:
      annotations:
        app.kubernetes.io/managed-by: disabled
    spec:
      syncPolicy: {}
    {{`{{- end }}`}}
    {{`{{- if hasKey . "syncPolicy" }}`}}
    spec:
      syncPolicy: {{`{{ toYaml .syncPolicy | nindent 8 }}`}}
    {{`{{- end }}`}}
    {{`{{- if hasKey . "ignoreDifferences" }}`}}
    spec:
      ignoreDifferences: {{`{{ toYaml .ignoreDifferences | nindent 8 }}`}}
    {{`{{- end }}`}}
