apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.appName" . }}
  namespace: {{ include "common.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "common.labels" . | nindent 4 }}
  ports:
    - port: 80
      targetPort: 80
