{{- $root := . -}}
{{- range $gateway := .Values.gateways }}
{{- $from := dig "allowedRoutes" "namespaces" "from" "All" $gateway }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ required "gateway.name is required" $gateway.name | quote }}
  namespace: {{ $root.Values.namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ $root.Chart.Name | quote }}
    app.kubernetes.io/instance: {{ $root.Release.Name | quote }}
    gateway.deokjong.io/exposure: {{ required "gateway.exposure is required" $gateway.exposure | quote }}
  {{- with $gateway.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ default $root.Values.gatewayClassName $gateway.gatewayClassName | quote }}
  listeners:
    - name: "http"
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: {{ $from | quote }}
    - name: "https"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
            name: {{ required "gateway.certificateRef.name is required" $gateway.certificateRef.name | quote }}
            namespace: {{ default $root.Values.namespace $gateway.certificateRef.namespace | quote }}
      allowedRoutes:
        namespaces:
          from: {{ $from | quote }}
    {{- range $gateway.extraListeners }}
    - {{ toYaml . | nindent 6 | trim }}
    {{- end }}
{{- end }}
