apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: foundation-istio-base
  annotations:
    argocd.argoproj.io/sync-wave: 0
spec:
  destination:
    server: {{ .Values.global.destination.server }}
    namespace: istio
  project: {{ .Values.global.project }}
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: base
    targetRevision: 1.30.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
