apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: foundation-istio-cni
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    server: {{ .Values.global.destination.server }}
    namespace: istio
  project: {{ .Values.global.project }}
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: cni
    targetRevision: 1.30.0
    helm:
      values: |
        profile: ambient
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true