apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: minecraft
  namespace: {{ include "minecraft.namespace" . }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ include "minecraft.hostname" . | quote }}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.route.gateway.name | quote }}
      namespace: {{ .Values.route.gateway.namespace | quote }}
      sectionName: {{ .Values.route.gateway.sectionName | quote }}
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: minecraft
          port: {{ .Values.service.port }}
          weight: 1
