global:
  destination:
    server: https://kubernetes.default.svc
  project: default

argocdNamespace: argocd
namespace: istio-system
appNamePrefix: foundation-istio

istio:
  repoURL: https://istio-release.storage.googleapis.com/charts
  version: 1.30.0

syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true

components:
  - chart: base
    enabled: true
    syncWave: "0"
    ignoreDifferences:
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
        jqPathExpressions:
          - .webhooks[]?.failurePolicy

  - chart: istiod
    enabled: true
    syncWave: "1"
    helmValues:
      profile: ambient
      pilot:
        env:
          PILOT_ENABLE_ALPHA_GATEWAY_API: "true"
    ignoreDifferences:
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
        jqPathExpressions:
          - .webhooks[]?.failurePolicy

  - chart: cni
    enabled: true
    syncWave: "2"
    helmValues:
      profile: ambient

  - chart: ztunnel
    enabled: true
    syncWave: "3"
