apiVersion: v2
name: actions-runners
description: GitHub Actions Runner v2
type: application
version: 0.1.0

dependencies:
  - name: actions-runner-controller
    version: 0.14.2
    repository: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller